---
driver:
  name: vagrant
  customize:
    cpus: 8
    memory: 4096

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[buildbot::default]
    attributes:
      apt:
        compile_time_update: true
