---
driver:
  name: vagrant
  customize:
    cpus: 8
    memory: 4096

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: master
    run_list:
      - recipe[buildbot::master]
    attributes:
      apt:
        compile_time_update: true
- name: slave
    run_list:
      - recipe[buildbot::slave]
    attributes:
      apt:
        compile_time_update: true
